/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ussu.pims.DAO;

import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Repository;
import ussu.pims.Mapper.ChartDataPointMapper;
import ussu.pims.Model.ChartDataPoint;

/**
 *
 * @author danielroy
 */
@Repository
public class DashboardDAO {

    @Autowired
    private JdbcTemplate jdbcTemplate;

    public List<ChartDataPoint> getAllTests7Days(int userId) {
        String SQL = ""
                + "SELECT\n"
                + "	all_tests.number_of_tests value\n"
                + ",	my_tests.my_number_of_tests my_value\n"
                + ", 	all_tests.test_date label\n"
                + "FROM (\n"
                + "	SELECT\n"
                + "		COUNT(*) number_of_tests\n"
                + ",  	DATE(NOW() - INTERVAL 6 DAY) test_date\n"
                + "	FROM pims.tests t\n"
                + "	WHERE DATE(t.test_datetime) = DATE(NOW() - INTERVAL 6 DAY)\n"
                + ") all_tests\n"
                + "JOIN (\n"
                + "	SELECT\n"
                + "		COUNT(*) my_number_of_tests\n"
                + "	, 	DATE(NOW() - INTERVAL 6 DAY) test_date\n"
                + "    FROM pims.tests t\n"
                + "    WHERE DATE(t.test_datetime) = DATE(NOW() - INTERVAL 6 DAY)\n"
                + "    AND t.test_user = ?\n"
                + ") my_tests ON all_tests.test_date = my_tests.test_date\n"
                + "UNION\n"
                + "SELECT\n"
                + "	all_tests.number_of_tests value\n"
                + ",	my_tests.my_number_of_tests my_value\n"
                + ", 	all_tests.test_date label\n"
                + "FROM (\n"
                + "	SELECT\n"
                + "		COUNT(*) number_of_tests\n"
                + ",  	DATE(NOW() - INTERVAL 5 DAY) test_date\n"
                + "	FROM pims.tests t\n"
                + "	WHERE DATE(t.test_datetime) = DATE(NOW() - INTERVAL 5 DAY)\n"
                + ") all_tests\n"
                + "JOIN (\n"
                + "	SELECT\n"
                + "		COUNT(*) my_number_of_tests\n"
                + "	, 	DATE(NOW() - INTERVAL 5 DAY) test_date\n"
                + "    FROM pims.tests t\n"
                + "    WHERE DATE(t.test_datetime) = DATE(NOW() - INTERVAL 5 DAY)\n"
                + "    AND t.test_user = ?\n"
                + ") my_tests ON all_tests.test_date = my_tests.test_date\n"
                + "UNION\n"
                + "SELECT\n"
                + "	all_tests.number_of_tests value\n"
                + ",	my_tests.my_number_of_tests my_value\n"
                + ", 	all_tests.test_date label\n"
                + "FROM (\n"
                + "	SELECT\n"
                + "		COUNT(*) number_of_tests\n"
                + ",  	DATE(NOW() - INTERVAL 4 DAY) test_date\n"
                + "	FROM pims.tests t\n"
                + "	WHERE DATE(t.test_datetime) = DATE(NOW() - INTERVAL 4 DAY)\n"
                + ") all_tests\n"
                + "JOIN (\n"
                + "	SELECT\n"
                + "		COUNT(*) my_number_of_tests\n"
                + "	, 	DATE(NOW() - INTERVAL 4 DAY) test_date\n"
                + "    FROM pims.tests t\n"
                + "    WHERE DATE(t.test_datetime) = DATE(NOW() - INTERVAL 4 DAY)\n"
                + "    AND t.test_user = ?\n"
                + ") my_tests ON all_tests.test_date = my_tests.test_date\n"
                + "UNION\n"
                + "SELECT\n"
                + "	all_tests.number_of_tests value\n"
                + ",	my_tests.my_number_of_tests my_value\n"
                + ", 	all_tests.test_date label\n"
                + "FROM (\n"
                + "	SELECT\n"
                + "		COUNT(*) number_of_tests\n"
                + ",  	DATE(NOW() - INTERVAL 3 DAY) test_date\n"
                + "	FROM pims.tests t\n"
                + "	WHERE DATE(t.test_datetime) = DATE(NOW() - INTERVAL 3 DAY)\n"
                + ") all_tests\n"
                + "JOIN (\n"
                + "	SELECT\n"
                + "		COUNT(*) my_number_of_tests\n"
                + "	, 	DATE(NOW() - INTERVAL 3 DAY) test_date\n"
                + "    FROM pims.tests t\n"
                + "    WHERE DATE(t.test_datetime) = DATE(NOW() - INTERVAL 3 DAY)\n"
                + "    AND t.test_user = ?\n"
                + ") my_tests ON all_tests.test_date = my_tests.test_date\n"
                + "UNION\n"
                + "SELECT\n"
                + "	all_tests.number_of_tests value\n"
                + ",	my_tests.my_number_of_tests my_value\n"
                + ", 	all_tests.test_date label\n"
                + "FROM (\n"
                + "	SELECT\n"
                + "		COUNT(*) number_of_tests\n"
                + ",  	DATE(NOW() - INTERVAL 2 DAY) test_date\n"
                + "	FROM pims.tests t\n"
                + "	WHERE DATE(t.test_datetime) = DATE(NOW() - INTERVAL 2 DAY)\n"
                + ") all_tests\n"
                + "JOIN (\n"
                + "	SELECT\n"
                + "		COUNT(*) my_number_of_tests\n"
                + "	, 	DATE(NOW() - INTERVAL 2 DAY) test_date\n"
                + "    FROM pims.tests t\n"
                + "    WHERE DATE(t.test_datetime) = DATE(NOW() - INTERVAL 2 DAY)\n"
                + "    AND t.test_user = ?\n"
                + ") my_tests ON all_tests.test_date = my_tests.test_date\n"
                + "UNION\n"
                + "SELECT\n"
                + "	all_tests.number_of_tests value\n"
                + ",	my_tests.my_number_of_tests my_value\n"
                + ", 	all_tests.test_date label\n"
                + "FROM (\n"
                + "	SELECT\n"
                + "		COUNT(*) number_of_tests\n"
                + ",  	DATE(NOW() - INTERVAL 1 DAY) test_date\n"
                + "	FROM pims.tests t\n"
                + "	WHERE DATE(t.test_datetime) = DATE(NOW() - INTERVAL 1 DAY)\n"
                + ") all_tests\n"
                + "JOIN (\n"
                + "	SELECT\n"
                + "		COUNT(*) my_number_of_tests\n"
                + "	, 	DATE(NOW() - INTERVAL 1 DAY) test_date\n"
                + "    FROM pims.tests t\n"
                + "    WHERE DATE(t.test_datetime) = DATE(NOW() - INTERVAL 1 DAY)\n"
                + "    AND t.test_user = ?\n"
                + ") my_tests ON all_tests.test_date = my_tests.test_date\n"
                + "UNION\n"
                + "SELECT\n"
                + "	all_tests.number_of_tests value\n"
                + ",	my_tests.my_number_of_tests my_value\n"
                + ", 	all_tests.test_date label\n"
                + "FROM (\n"
                + "	SELECT\n"
                + "		COUNT(*) number_of_tests\n"
                + ",  	DATE(NOW() - INTERVAL 0 DAY) test_date\n"
                + "	FROM pims.tests t\n"
                + "	WHERE DATE(t.test_datetime) = DATE(NOW() - INTERVAL 0 DAY)\n"
                + ") all_tests\n"
                + "JOIN (\n"
                + "	SELECT\n"
                + "		COUNT(*) my_number_of_tests\n"
                + "	, 	DATE(NOW() - INTERVAL 0 DAY) test_date\n"
                + "    FROM pims.tests t\n"
                + "    WHERE DATE(t.test_datetime) = DATE(NOW() - INTERVAL 0 DAY)\n"
                + "    AND t.test_user = ?\n"
                + ") my_tests ON all_tests.test_date = my_tests.test_date";
        return jdbcTemplate.query(SQL, new ChartDataPointMapper(), userId, userId, userId, userId, userId, userId, userId);
    }

    public List<ChartDataPoint> getAllTests14Days(int userId) {
        String SQL = ""
                + "SELECT\n"
                + "	all_tests.number_of_tests value\n"
                + ",	my_tests.my_number_of_tests my_value\n"
                + ", 	all_tests.test_date label\n"
                + "FROM (\n"
                + "	SELECT\n"
                + "		COUNT(*) number_of_tests\n"
                + ",  	DAY(DATE(NOW() - INTERVAL 14 DAY)) test_date\n"
                + "	FROM pims.tests t\n"
                + "	WHERE DATE(t.test_datetime) = DATE(NOW() - INTERVAL 14 DAY)\n"
                + ") all_tests\n"
                + "JOIN (\n"
                + "	SELECT\n"
                + "		COUNT(*) my_number_of_tests\n"
                + "	, 	DAY(DATE(NOW() - INTERVAL 14 DAY)) test_date\n"
                + "    FROM pims.tests t\n"
                + "    WHERE DATE(t.test_datetime) = DATE(NOW() - INTERVAL 14 DAY)\n"
                + "    AND t.test_user = ?\n"
                + ") my_tests ON all_tests.test_date = my_tests.test_date\n"
                + "UNION\n"
                + "SELECT\n"
                + "	all_tests.number_of_tests value\n"
                + ",	my_tests.my_number_of_tests my_value\n"
                + ", 	all_tests.test_date label\n"
                + "FROM (\n"
                + "	SELECT\n"
                + "		COUNT(*) number_of_tests\n"
                + ",  	DAY(DATE(NOW() - INTERVAL 13 DAY)) test_date\n"
                + "	FROM pims.tests t\n"
                + "	WHERE DATE(t.test_datetime) = DATE(NOW() - INTERVAL 13 DAY)\n"
                + ") all_tests\n"
                + "JOIN (\n"
                + "	SELECT\n"
                + "		COUNT(*) my_number_of_tests\n"
                + "	, 	DAY(DATE(NOW() - INTERVAL 13 DAY)) test_date\n"
                + "    FROM pims.tests t\n"
                + "    WHERE DATE(t.test_datetime) = DATE(NOW() - INTERVAL 13 DAY)\n"
                + "    AND t.test_user = ?\n"
                + ") my_tests ON all_tests.test_date = my_tests.test_date\n"
                + "UNION\n"
                + "SELECT\n"
                + "	all_tests.number_of_tests value\n"
                + ",	my_tests.my_number_of_tests my_value\n"
                + ", 	all_tests.test_date label\n"
                + "FROM (\n"
                + "	SELECT\n"
                + "		COUNT(*) number_of_tests\n"
                + ",  	DAY(DATE(NOW() - INTERVAL 12 DAY)) test_date\n"
                + "	FROM pims.tests t\n"
                + "	WHERE DATE(t.test_datetime) = DATE(NOW() - INTERVAL 12 DAY)\n"
                + ") all_tests\n"
                + "JOIN (\n"
                + "	SELECT\n"
                + "		COUNT(*) my_number_of_tests\n"
                + "	, 	DAY(DATE(NOW() - INTERVAL 12 DAY)) test_date\n"
                + "    FROM pims.tests t\n"
                + "    WHERE DATE(t.test_datetime) = DATE(NOW() - INTERVAL 12 DAY)\n"
                + "    AND t.test_user = ?\n"
                + ") my_tests ON all_tests.test_date = my_tests.test_date\n"
                + "UNION\n"
                + "SELECT\n"
                + "	all_tests.number_of_tests value\n"
                + ",	my_tests.my_number_of_tests my_value\n"
                + ", 	all_tests.test_date label\n"
                + "FROM (\n"
                + "	SELECT\n"
                + "		COUNT(*) number_of_tests\n"
                + ",  	DAY(DATE(NOW() - INTERVAL 11 DAY)) test_date\n"
                + "	FROM pims.tests t\n"
                + "	WHERE DATE(t.test_datetime) = DATE(NOW() - INTERVAL 11 DAY)\n"
                + ") all_tests\n"
                + "JOIN (\n"
                + "	SELECT\n"
                + "		COUNT(*) my_number_of_tests\n"
                + "	, 	DAY(DATE(NOW() - INTERVAL 11 DAY)) test_date\n"
                + "    FROM pims.tests t\n"
                + "    WHERE DATE(t.test_datetime) = DATE(NOW() - INTERVAL 11 DAY)\n"
                + "    AND t.test_user = ?\n"
                + ") my_tests ON all_tests.test_date = my_tests.test_date\n"
                + "UNION\n"
                + "SELECT\n"
                + "	all_tests.number_of_tests value\n"
                + ",	my_tests.my_number_of_tests my_value\n"
                + ", 	all_tests.test_date label\n"
                + "FROM (\n"
                + "	SELECT\n"
                + "		COUNT(*) number_of_tests\n"
                + ",  	DAY(DATE(NOW() - INTERVAL 10 DAY)) test_date\n"
                + "	FROM pims.tests t\n"
                + "	WHERE DATE(t.test_datetime) = DATE(NOW() - INTERVAL 10 DAY)\n"
                + ") all_tests\n"
                + "JOIN (\n"
                + "	SELECT\n"
                + "		COUNT(*) my_number_of_tests\n"
                + "	, 	DAY(DATE(NOW() - INTERVAL 10 DAY)) test_date\n"
                + "    FROM pims.tests t\n"
                + "    WHERE DATE(t.test_datetime) = DATE(NOW() - INTERVAL 10 DAY)\n"
                + "    AND t.test_user = ?\n"
                + ") my_tests ON all_tests.test_date = my_tests.test_date\n"
                + "UNION\n"
                + "SELECT\n"
                + "	all_tests.number_of_tests value\n"
                + ",	my_tests.my_number_of_tests my_value\n"
                + ", 	all_tests.test_date label\n"
                + "FROM (\n"
                + "	SELECT\n"
                + "		COUNT(*) number_of_tests\n"
                + ",  	DAY(DATE(NOW() - INTERVAL 9 DAY)) test_date\n"
                + "	FROM pims.tests t\n"
                + "	WHERE DATE(t.test_datetime) = DATE(NOW() - INTERVAL 9 DAY)\n"
                + ") all_tests\n"
                + "JOIN (\n"
                + "	SELECT\n"
                + "		COUNT(*) my_number_of_tests\n"
                + "	, 	DAY(DATE(NOW() - INTERVAL 9 DAY)) test_date\n"
                + "    FROM pims.tests t\n"
                + "    WHERE DATE(t.test_datetime) = DATE(NOW() - INTERVAL 9 DAY)\n"
                + "    AND t.test_user = ?\n"
                + ") my_tests ON all_tests.test_date = my_tests.test_date\n"
                + "UNION\n"
                + "SELECT\n"
                + "	all_tests.number_of_tests value\n"
                + ",	my_tests.my_number_of_tests my_value\n"
                + ", 	all_tests.test_date label\n"
                + "FROM (\n"
                + "	SELECT\n"
                + "		COUNT(*) number_of_tests\n"
                + ",  	DAY(DATE(NOW() - INTERVAL 8 DAY)) test_date\n"
                + "	FROM pims.tests t\n"
                + "	WHERE DATE(t.test_datetime) = DATE(NOW() - INTERVAL 8 DAY)\n"
                + ") all_tests\n"
                + "JOIN (\n"
                + "	SELECT\n"
                + "		COUNT(*) my_number_of_tests\n"
                + "	, 	DAY(DATE(NOW() - INTERVAL 8 DAY)) test_date\n"
                + "    FROM pims.tests t\n"
                + "    WHERE DATE(t.test_datetime) = DATE(NOW() - INTERVAL 8 DAY)\n"
                + "    AND t.test_user = ?\n"
                + ") my_tests ON all_tests.test_date = my_tests.test_date\n"
                + "UNION\n"
                + "SELECT\n"
                + "	all_tests.number_of_tests value\n"
                + ",	my_tests.my_number_of_tests my_value\n"
                + ", 	all_tests.test_date label\n"
                + "FROM (\n"
                + "	SELECT\n"
                + "		COUNT(*) number_of_tests\n"
                + ",  	DAY(DATE(NOW() - INTERVAL 7 DAY)) test_date\n"
                + "	FROM pims.tests t\n"
                + "	WHERE DATE(t.test_datetime) = DATE(NOW() - INTERVAL 7 DAY)\n"
                + ") all_tests\n"
                + "JOIN (\n"
                + "	SELECT\n"
                + "		COUNT(*) my_number_of_tests\n"
                + "	, 	DAY(DATE(NOW() - INTERVAL 7 DAY)) test_date\n"
                + "    FROM pims.tests t\n"
                + "    WHERE DATE(t.test_datetime) = DATE(NOW() - INTERVAL 7 DAY)\n"
                + "    AND t.test_user = ?\n"
                + ") my_tests ON all_tests.test_date = my_tests.test_date\n"
                + "UNION\n"
                + "SELECT\n"
                + "	all_tests.number_of_tests value\n"
                + ",	my_tests.my_number_of_tests my_value\n"
                + ", 	all_tests.test_date label\n"
                + "FROM (\n"
                + "	SELECT\n"
                + "		COUNT(*) number_of_tests\n"
                + ",  	DAY(DATE(NOW() - INTERVAL 6 DAY)) test_date\n"
                + "	FROM pims.tests t\n"
                + "	WHERE DATE(t.test_datetime) = DATE(NOW() - INTERVAL 6 DAY)\n"
                + ") all_tests\n"
                + "JOIN (\n"
                + "	SELECT\n"
                + "		COUNT(*) my_number_of_tests\n"
                + "	, 	DAY(DATE(NOW() - INTERVAL 6 DAY)) test_date\n"
                + "    FROM pims.tests t\n"
                + "    WHERE DATE(t.test_datetime) = DATE(NOW() - INTERVAL 6 DAY)\n"
                + "    AND t.test_user = ?\n"
                + ") my_tests ON all_tests.test_date = my_tests.test_date\n"
                + "UNION\n"
                + "SELECT\n"
                + "	all_tests.number_of_tests value\n"
                + ",	my_tests.my_number_of_tests my_value\n"
                + ", 	all_tests.test_date label\n"
                + "FROM (\n"
                + "	SELECT\n"
                + "		COUNT(*) number_of_tests\n"
                + ",  	DAY(DATE(NOW() - INTERVAL 5 DAY)) test_date\n"
                + "	FROM pims.tests t\n"
                + "	WHERE DATE(t.test_datetime) = DATE(NOW() - INTERVAL 5 DAY)\n"
                + ") all_tests\n"
                + "JOIN (\n"
                + "	SELECT\n"
                + "		COUNT(*) my_number_of_tests\n"
                + "	, 	DAY(DATE(NOW() - INTERVAL 5 DAY)) test_date\n"
                + "    FROM pims.tests t\n"
                + "    WHERE DATE(t.test_datetime) = DATE(NOW() - INTERVAL 5 DAY)\n"
                + "    AND t.test_user = ?\n"
                + ") my_tests ON all_tests.test_date = my_tests.test_date\n"
                + "UNION\n"
                + "SELECT\n"
                + "	all_tests.number_of_tests value\n"
                + ",	my_tests.my_number_of_tests my_value\n"
                + ", 	all_tests.test_date label\n"
                + "FROM (\n"
                + "	SELECT\n"
                + "		COUNT(*) number_of_tests\n"
                + ",  	DAY(DATE(NOW() - INTERVAL 4 DAY)) test_date\n"
                + "	FROM pims.tests t\n"
                + "	WHERE DATE(t.test_datetime) = DATE(NOW() - INTERVAL 4 DAY)\n"
                + ") all_tests\n"
                + "JOIN (\n"
                + "	SELECT\n"
                + "		COUNT(*) my_number_of_tests\n"
                + "	, 	DAY(DATE(NOW() - INTERVAL 4 DAY)) test_date\n"
                + "    FROM pims.tests t\n"
                + "    WHERE DATE(t.test_datetime) = DATE(NOW() - INTERVAL 4 DAY)\n"
                + "    AND t.test_user = ?\n"
                + ") my_tests ON all_tests.test_date = my_tests.test_date\n"
                + "UNION\n"
                + "SELECT\n"
                + "	all_tests.number_of_tests value\n"
                + ",	my_tests.my_number_of_tests my_value\n"
                + ", 	all_tests.test_date label\n"
                + "FROM (\n"
                + "	SELECT\n"
                + "		COUNT(*) number_of_tests\n"
                + ",  	DAY(DATE(NOW() - INTERVAL 3 DAY)) test_date\n"
                + "	FROM pims.tests t\n"
                + "	WHERE DATE(t.test_datetime) = DATE(NOW() - INTERVAL 3 DAY)\n"
                + ") all_tests\n"
                + "JOIN (\n"
                + "	SELECT\n"
                + "		COUNT(*) my_number_of_tests\n"
                + "	, 	DAY(DATE(NOW() - INTERVAL 3 DAY)) test_date\n"
                + "    FROM pims.tests t\n"
                + "    WHERE DATE(t.test_datetime) = DATE(NOW() - INTERVAL 3 DAY)\n"
                + "    AND t.test_user = ?\n"
                + ") my_tests ON all_tests.test_date = my_tests.test_date\n"
                + "UNION\n"
                + "SELECT\n"
                + "	all_tests.number_of_tests value\n"
                + ",	my_tests.my_number_of_tests my_value\n"
                + ", 	all_tests.test_date label\n"
                + "FROM (\n"
                + "	SELECT\n"
                + "		COUNT(*) number_of_tests\n"
                + ",  	DAY(DATE(NOW() - INTERVAL 2 DAY)) test_date\n"
                + "	FROM pims.tests t\n"
                + "	WHERE DATE(t.test_datetime) = DATE(NOW() - INTERVAL 2 DAY)\n"
                + ") all_tests\n"
                + "JOIN (\n"
                + "	SELECT\n"
                + "		COUNT(*) my_number_of_tests\n"
                + "	, 	DAY(DATE(NOW() - INTERVAL 2 DAY)) test_date\n"
                + "    FROM pims.tests t\n"
                + "    WHERE DATE(t.test_datetime) = DATE(NOW() - INTERVAL 2 DAY)\n"
                + "    AND t.test_user = ?\n"
                + ") my_tests ON all_tests.test_date = my_tests.test_date\n"
                + "UNION\n"
                + "SELECT\n"
                + "	all_tests.number_of_tests value\n"
                + ",	my_tests.my_number_of_tests my_value\n"
                + ", 	all_tests.test_date label\n"
                + "FROM (\n"
                + "	SELECT\n"
                + "		COUNT(*) number_of_tests\n"
                + ",  	DAY(DATE(NOW() - INTERVAL 1 DAY)) test_date\n"
                + "	FROM pims.tests t\n"
                + "	WHERE DATE(t.test_datetime) = DATE(NOW() - INTERVAL 1 DAY)\n"
                + ") all_tests\n"
                + "JOIN (\n"
                + "	SELECT\n"
                + "		COUNT(*) my_number_of_tests\n"
                + "	, 	DAY(DATE(NOW() - INTERVAL 1 DAY)) test_date\n"
                + "    FROM pims.tests t\n"
                + "    WHERE DATE(t.test_datetime) = DATE(NOW() - INTERVAL 1 DAY)\n"
                + "    AND t.test_user = ?\n"
                + ") my_tests ON all_tests.test_date = my_tests.test_date\n"
                + "UNION\n"
                + "SELECT\n"
                + "	all_tests.number_of_tests value\n"
                + ",	my_tests.my_number_of_tests my_value\n"
                + ", 	all_tests.test_date label\n"
                + "FROM (\n"
                + "	SELECT\n"
                + "		COUNT(*) number_of_tests\n"
                + ",  	DAY(DATE(NOW() - INTERVAL 0 DAY)) test_date\n"
                + "	FROM pims.tests t\n"
                + "	WHERE DATE(t.test_datetime) = DATE(NOW() - INTERVAL 0 DAY)\n"
                + ") all_tests\n"
                + "JOIN (\n"
                + "	SELECT\n"
                + "		COUNT(*) my_number_of_tests\n"
                + "	, 	DAY(DATE(NOW() - INTERVAL 0 DAY)) test_date\n"
                + "    FROM pims.tests t\n"
                + "    WHERE DATE(t.test_datetime) = DATE(NOW() - INTERVAL 0 DAY)\n"
                + "    AND t.test_user = ?\n"
                + ") my_tests ON all_tests.test_date = my_tests.test_date";
        return jdbcTemplate.query(SQL, new ChartDataPointMapper(), userId, userId, userId, userId, userId, userId, userId, userId, userId, userId, userId, userId, userId, userId, userId);
    }

    public List<ChartDataPoint> getAllTests1Year(int userID) {
        String SQL = ""
                + "SELECT\n"
                + "	all_tests.number_of_tests value\n"
                + ",	my_tests.my_number_of_tests my_value\n"
                + ", 	all_tests.test_date label\n"
                + "FROM (\n"
                + "	SELECT\n"
                + "		COUNT(*) number_of_tests\n"
                + ",  	MONTH(DATE(NOW() - INTERVAL 11 MONTH)) test_date\n"
                + "	FROM pims.tests t\n"
                + "	WHERE MONTH(DATE(t.test_datetime)) = MONTH(DATE(NOW() - INTERVAL 11 MONTH))\n"
                + "    AND YEAR(DATE(t.test_datetime)) = YEAR(DATE(NOW() - INTERVAL 11 MONTH))\n"
                + ") all_tests\n"
                + "JOIN (\n"
                + "	SELECT\n"
                + "		COUNT(*) my_number_of_tests\n"
                + "	, 	MONTH(DATE(NOW() - INTERVAL 11 MONTH)) test_date\n"
                + "    FROM pims.tests t\n"
                + "    WHERE MONTH(DATE(t.test_datetime)) = MONTH(DATE(NOW() - INTERVAL 11 MONTH))\n"
                + "    AND YEAR(DATE(t.test_datetime)) = YEAR(DATE(NOW() - INTERVAL 11 MONTH))\n"
                + "    AND t.test_user = ?\n"
                + ") my_tests ON all_tests.test_date = my_tests.test_date\n"
                + "UNION\n"
                + "SELECT\n"
                + "	all_tests.number_of_tests value\n"
                + ",	my_tests.my_number_of_tests my_value\n"
                + ", 	all_tests.test_date label\n"
                + "FROM (\n"
                + "	SELECT\n"
                + "		COUNT(*) number_of_tests\n"
                + ",  	MONTH(DATE(NOW() - INTERVAL 110 MONTH)) test_date\n"
                + "	FROM pims.tests t\n"
                + "	WHERE MONTH(DATE(t.test_datetime)) = MONTH(DATE(NOW() - INTERVAL 10 MONTH))\n"
                + "    AND YEAR(DATE(t.test_datetime)) = YEAR(DATE(NOW() - INTERVAL 10 MONTH))\n"
                + ") all_tests\n"
                + "JOIN (\n"
                + "	SELECT\n"
                + "		COUNT(*) my_number_of_tests\n"
                + "	, 	MONTH(DATE(NOW() - INTERVAL 10 MONTH)) test_date\n"
                + "    FROM pims.tests t\n"
                + "    WHERE MONTH(DATE(t.test_datetime)) = MONTH(DATE(NOW() - INTERVAL 10 MONTH))\n"
                + "    AND YEAR(DATE(t.test_datetime)) = YEAR(DATE(NOW() - INTERVAL 10 MONTH))\n"
                + "    AND t.test_user = ?\n"
                + ") my_tests ON all_tests.test_date = my_tests.test_date\n"
                + "UNION\n"
                + "SELECT\n"
                + "	all_tests.number_of_tests value\n"
                + ",	my_tests.my_number_of_tests my_value\n"
                + ", 	all_tests.test_date label\n"
                + "FROM (\n"
                + "	SELECT\n"
                + "		COUNT(*) number_of_tests\n"
                + ",  	MONTH(DATE(NOW() - INTERVAL 9 MONTH)) test_date\n"
                + "	FROM pims.tests t\n"
                + "	WHERE MONTH(DATE(t.test_datetime)) = MONTH(DATE(NOW() - INTERVAL 9 MONTH))\n"
                + "    AND YEAR(DATE(t.test_datetime)) = YEAR(DATE(NOW() - INTERVAL 9 MONTH))\n"
                + ") all_tests\n"
                + "JOIN (\n"
                + "	SELECT\n"
                + "		COUNT(*) my_number_of_tests\n"
                + "	, 	MONTH(DATE(NOW() - INTERVAL 9 MONTH)) test_date\n"
                + "    FROM pims.tests t\n"
                + "    WHERE MONTH(DATE(t.test_datetime)) = MONTH(DATE(NOW() - INTERVAL 9 MONTH))\n"
                + "    AND YEAR(DATE(t.test_datetime)) = YEAR(DATE(NOW() - INTERVAL 9 MONTH))\n"
                + "    AND t.test_user = ?\n"
                + ") my_tests ON all_tests.test_date = my_tests.test_date\n"
                + "UNION\n"
                + "SELECT\n"
                + "	all_tests.number_of_tests value\n"
                + ",	my_tests.my_number_of_tests my_value\n"
                + ", 	all_tests.test_date label\n"
                + "FROM (\n"
                + "	SELECT\n"
                + "		COUNT(*) number_of_tests\n"
                + ",  	MONTH(DATE(NOW() - INTERVAL 8 MONTH)) test_date\n"
                + "	FROM pims.tests t\n"
                + "	WHERE MONTH(DATE(t.test_datetime)) = MONTH(DATE(NOW() - INTERVAL 8 MONTH))\n"
                + "    AND YEAR(DATE(t.test_datetime)) = YEAR(DATE(NOW() - INTERVAL 8 MONTH))\n"
                + ") all_tests\n"
                + "JOIN (\n"
                + "	SELECT\n"
                + "		COUNT(*) my_number_of_tests\n"
                + "	, 	MONTH(DATE(NOW() - INTERVAL 8 MONTH)) test_date\n"
                + "    FROM pims.tests t\n"
                + "    WHERE MONTH(DATE(t.test_datetime)) = MONTH(DATE(NOW() - INTERVAL 8 MONTH))\n"
                + "    AND YEAR(DATE(t.test_datetime)) = YEAR(DATE(NOW() - INTERVAL 8 MONTH))\n"
                + "    AND t.test_user = ?\n"
                + ") my_tests ON all_tests.test_date = my_tests.test_date\n"
                + "UNION\n"
                + "SELECT\n"
                + "	all_tests.number_of_tests value\n"
                + ",	my_tests.my_number_of_tests my_value\n"
                + ", 	all_tests.test_date label\n"
                + "FROM (\n"
                + "	SELECT\n"
                + "		COUNT(*) number_of_tests\n"
                + ",  	MONTH(DATE(NOW() - INTERVAL 7 MONTH)) test_date\n"
                + "	FROM pims.tests t\n"
                + "	WHERE MONTH(DATE(t.test_datetime)) = MONTH(DATE(NOW() - INTERVAL 7 MONTH))\n"
                + "    AND YEAR(DATE(t.test_datetime)) = YEAR(DATE(NOW() - INTERVAL 7 MONTH))\n"
                + ") all_tests\n"
                + "JOIN (\n"
                + "	SELECT\n"
                + "		COUNT(*) my_number_of_tests\n"
                + "	, 	MONTH(DATE(NOW() - INTERVAL 7 MONTH)) test_date\n"
                + "    FROM pims.tests t\n"
                + "    WHERE MONTH(DATE(t.test_datetime)) = MONTH(DATE(NOW() - INTERVAL 7 MONTH))\n"
                + "    AND YEAR(DATE(t.test_datetime)) = YEAR(DATE(NOW() - INTERVAL 7 MONTH))\n"
                + "    AND t.test_user = ?\n"
                + ") my_tests ON all_tests.test_date = my_tests.test_date\n"
                + "UNION\n"
                + "SELECT\n"
                + "	all_tests.number_of_tests value\n"
                + ",	my_tests.my_number_of_tests my_value\n"
                + ", 	all_tests.test_date label\n"
                + "FROM (\n"
                + "	SELECT\n"
                + "		COUNT(*) number_of_tests\n"
                + ",  	MONTH(DATE(NOW() - INTERVAL 6 MONTH)) test_date\n"
                + "	FROM pims.tests t\n"
                + "	WHERE MONTH(DATE(t.test_datetime)) = MONTH(DATE(NOW() - INTERVAL 6 MONTH))\n"
                + "    AND YEAR(DATE(t.test_datetime)) = YEAR(DATE(NOW() - INTERVAL 6 MONTH))\n"
                + ") all_tests\n"
                + "JOIN (\n"
                + "	SELECT\n"
                + "		COUNT(*) my_number_of_tests\n"
                + "	, 	MONTH(DATE(NOW() - INTERVAL 6 MONTH)) test_date\n"
                + "    FROM pims.tests t\n"
                + "    WHERE MONTH(DATE(t.test_datetime)) = MONTH(DATE(NOW() - INTERVAL 6 MONTH))\n"
                + "    AND YEAR(DATE(t.test_datetime)) = YEAR(DATE(NOW() - INTERVAL 6 MONTH))\n"
                + "    AND t.test_user = ?\n"
                + ") my_tests ON all_tests.test_date = my_tests.test_date\n"
                + "UNION\n"
                + "SELECT\n"
                + "	all_tests.number_of_tests value\n"
                + ",	my_tests.my_number_of_tests my_value\n"
                + ", 	all_tests.test_date label\n"
                + "FROM (\n"
                + "	SELECT\n"
                + "		COUNT(*) number_of_tests\n"
                + ",  	MONTH(DATE(NOW() - INTERVAL 5 MONTH)) test_date\n"
                + "	FROM pims.tests t\n"
                + "	WHERE MONTH(DATE(t.test_datetime)) = MONTH(DATE(NOW() - INTERVAL 5 MONTH))\n"
                + "    AND YEAR(DATE(t.test_datetime)) = YEAR(DATE(NOW() - INTERVAL 5 MONTH))\n"
                + ") all_tests\n"
                + "JOIN (\n"
                + "	SELECT\n"
                + "		COUNT(*) my_number_of_tests\n"
                + "	, 	MONTH(DATE(NOW() - INTERVAL 5 MONTH)) test_date\n"
                + "    FROM pims.tests t\n"
                + "    WHERE MONTH(DATE(t.test_datetime)) = MONTH(DATE(NOW() - INTERVAL 5 MONTH))\n"
                + "    AND YEAR(DATE(t.test_datetime)) = YEAR(DATE(NOW() - INTERVAL 5 MONTH))\n"
                + "    AND t.test_user = ?\n"
                + ") my_tests ON all_tests.test_date = my_tests.test_date\n"
                + "UNION\n"
                + "SELECT\n"
                + "	all_tests.number_of_tests value\n"
                + ",	my_tests.my_number_of_tests my_value\n"
                + ", 	all_tests.test_date label\n"
                + "FROM (\n"
                + "	SELECT\n"
                + "		COUNT(*) number_of_tests\n"
                + ",  	MONTH(DATE(NOW() - INTERVAL 4 MONTH)) test_date\n"
                + "	FROM pims.tests t\n"
                + "	WHERE MONTH(DATE(t.test_datetime)) = MONTH(DATE(NOW() - INTERVAL 4 MONTH))\n"
                + "    AND YEAR(DATE(t.test_datetime)) = YEAR(DATE(NOW() - INTERVAL 4 MONTH))\n"
                + ") all_tests\n"
                + "JOIN (\n"
                + "	SELECT\n"
                + "		COUNT(*) my_number_of_tests\n"
                + "	, 	MONTH(DATE(NOW() - INTERVAL 4 MONTH)) test_date\n"
                + "    FROM pims.tests t\n"
                + "    WHERE MONTH(DATE(t.test_datetime)) = MONTH(DATE(NOW() - INTERVAL 4 MONTH))\n"
                + "    AND YEAR(DATE(t.test_datetime)) = YEAR(DATE(NOW() - INTERVAL 4 MONTH))\n"
                + "    AND t.test_user = ?\n"
                + ") my_tests ON all_tests.test_date = my_tests.test_date\n"
                + "UNION\n"
                + "SELECT\n"
                + "	all_tests.number_of_tests value\n"
                + ",	my_tests.my_number_of_tests my_value\n"
                + ", 	all_tests.test_date label\n"
                + "FROM (\n"
                + "	SELECT\n"
                + "		COUNT(*) number_of_tests\n"
                + ",  	MONTH(DATE(NOW() - INTERVAL 3 MONTH)) test_date\n"
                + "	FROM pims.tests t\n"
                + "	WHERE MONTH(DATE(t.test_datetime)) = MONTH(DATE(NOW() - INTERVAL 3 MONTH))\n"
                + "    AND YEAR(DATE(t.test_datetime)) = YEAR(DATE(NOW() - INTERVAL 3 MONTH))\n"
                + ") all_tests\n"
                + "JOIN (\n"
                + "	SELECT\n"
                + "		COUNT(*) my_number_of_tests\n"
                + "	, 	MONTH(DATE(NOW() - INTERVAL 3 MONTH)) test_date\n"
                + "    FROM pims.tests t\n"
                + "    WHERE MONTH(DATE(t.test_datetime)) = MONTH(DATE(NOW() - INTERVAL 3 MONTH))\n"
                + "    AND YEAR(DATE(t.test_datetime)) = YEAR(DATE(NOW() - INTERVAL 3 MONTH))\n"
                + "    AND t.test_user = ?\n"
                + ") my_tests ON all_tests.test_date = my_tests.test_date\n"
                + "UNION\n"
                + "SELECT\n"
                + "	all_tests.number_of_tests value\n"
                + ",	my_tests.my_number_of_tests my_value\n"
                + ", 	all_tests.test_date label\n"
                + "FROM (\n"
                + "	SELECT\n"
                + "		COUNT(*) number_of_tests\n"
                + ",  	MONTH(DATE(NOW() - INTERVAL 2 MONTH)) test_date\n"
                + "	FROM pims.tests t\n"
                + "	WHERE MONTH(DATE(t.test_datetime)) = MONTH(DATE(NOW() - INTERVAL 2 MONTH))\n"
                + "    AND YEAR(DATE(t.test_datetime)) = YEAR(DATE(NOW() - INTERVAL 2 MONTH))\n"
                + ") all_tests\n"
                + "JOIN (\n"
                + "	SELECT\n"
                + "		COUNT(*) my_number_of_tests\n"
                + "	, 	MONTH(DATE(NOW() - INTERVAL 2 MONTH)) test_date\n"
                + "    FROM pims.tests t\n"
                + "    WHERE MONTH(DATE(t.test_datetime)) = MONTH(DATE(NOW() - INTERVAL 2 MONTH))\n"
                + "    AND YEAR(DATE(t.test_datetime)) = YEAR(DATE(NOW() - INTERVAL 2 MONTH))\n"
                + "    AND t.test_user = ?\n"
                + ") my_tests ON all_tests.test_date = my_tests.test_date\n"
                + "UNION\n"
                + "SELECT\n"
                + "	all_tests.number_of_tests value\n"
                + ",	my_tests.my_number_of_tests my_value\n"
                + ", 	all_tests.test_date label\n"
                + "FROM (\n"
                + "	SELECT\n"
                + "		COUNT(*) number_of_tests\n"
                + ",  	MONTH(DATE(NOW() - INTERVAL 1 MONTH)) test_date\n"
                + "	FROM pims.tests t\n"
                + "	WHERE MONTH(DATE(t.test_datetime)) = MONTH(DATE(NOW() - INTERVAL 1 MONTH))\n"
                + "    AND YEAR(DATE(t.test_datetime)) = YEAR(DATE(NOW() - INTERVAL 1 MONTH))\n"
                + ") all_tests\n"
                + "JOIN (\n"
                + "	SELECT\n"
                + "		COUNT(*) my_number_of_tests\n"
                + "	, 	MONTH(DATE(NOW() - INTERVAL 1 MONTH)) test_date\n"
                + "    FROM pims.tests t\n"
                + "    WHERE MONTH(DATE(t.test_datetime)) = MONTH(DATE(NOW() - INTERVAL 1 MONTH))\n"
                + "    AND YEAR(DATE(t.test_datetime)) = YEAR(DATE(NOW() - INTERVAL 1 MONTH))\n"
                + "    AND t.test_user = ?\n"
                + ") my_tests ON all_tests.test_date = my_tests.test_date\n"
                + "UNION\n"
                + "SELECT\n"
                + "	all_tests.number_of_tests value\n"
                + ",	my_tests.my_number_of_tests my_value\n"
                + ", 	all_tests.test_date label\n"
                + "FROM (\n"
                + "	SELECT\n"
                + "		COUNT(*) number_of_tests\n"
                + ",  	MONTH(DATE(NOW() - INTERVAL 0 MONTH)) test_date\n"
                + "	FROM pims.tests t\n"
                + "	WHERE MONTH(DATE(t.test_datetime)) = MONTH(DATE(NOW() - INTERVAL 0 MONTH))\n"
                + "    AND YEAR(DATE(t.test_datetime)) = YEAR(DATE(NOW() - INTERVAL 0 MONTH))\n"
                + ") all_tests\n"
                + "JOIN (\n"
                + "	SELECT\n"
                + "		COUNT(*) my_number_of_tests\n"
                + "	, 	MONTH(DATE(NOW() - INTERVAL 0 MONTH)) test_date\n"
                + "    FROM pims.tests t\n"
                + "    WHERE MONTH(DATE(t.test_datetime)) = MONTH(DATE(NOW() - INTERVAL 0 MONTH))\n"
                + "    AND YEAR(DATE(t.test_datetime)) = YEAR(DATE(NOW() - INTERVAL 0 MONTH))\n"
                + "    AND t.test_user = ?\n"
                + ") my_tests ON all_tests.test_date = my_tests.test_date;";
        return jdbcTemplate.query(SQL, new ChartDataPointMapper(), userID, userID, userID, userID, userID, userID, userID, userID, userID, userID, userID, userID);
    }

}
